# Generated by Django 5.2.3 on 2025-06-22 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='articles.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='articles.tag'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-publish_date'], name='articles_ar_publish_b0da20_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='articles_ar_status_edb746_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured'], name='articles_ar_is_feat_d43b7b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_trending'], name='articles_ar_is_tren_9412e4_idx'),
        ),
    ]
