# Generated by Django 5.2.3 on 2025-06-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='lead_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
